import { ReceiptElement } from "@/components/pages/PageStrukManualClient";

export const LIST_BANK = [
  "BCA", "BRI", "Mandiri", "BNI", "BSI", "BTN", "CIMB Niaga", 
  "Permata", "OCBC NISP", "Danamon", "Bank Mega", "BTPN", 
  "Bank Jago", "Allo Bank", "SeaBank", "Blu by BCA Digital"
];

export const SIDEBAR = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "Layout Struk", href: "/dashboard/layout_list", icon: "LayersPlus" },
  { label: "Settings", href: "/dashboard/settings", icon: "Settings" },
  { label: "History", href: "/dashboard/history", icon: "Timer" },  
]

export const weightConstanta = {
  reg: 400,
  semi: 500,
  bold: 700
};

export const fontConfig = {
  name: 'Roboto Mono',
  googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100..700&display=swap',
  fallback: "'Consolas', monospace"
};

export const fontInternal = [
  {
    name: "Merchant Copy",
    fallback: "'Consolas', monospace",
    variants: [
      { weight: "reg", path: '/font/MerchantCopy.ttf' },  
      { weight: "semi", path: "/font/MerchantCopyWide.ttf" },
      { weight: "bold", path: '/font/MerchantCopyDoublesize.ttf' }
    ]
  }
]

export const ROLES = [
  { id: "1", label: "Admin", value: "admin" },
  { id: "2", label: "User", value: "user" }
]

export const NOT_SHOW_IN_PREVIEW = ['Hidden', 'total_keseluruhan', 'Admin_Fee', 'Store_Name', 'Alamat_Toko'];
export const NOT_TASK_AI_TYPE_INPUT = ['Hidden', 'total_keseluruhan', 'Admin_Fee', 'Store_Name', 'Alamat_Toko'];

export const DEFAULT_LOGO_RECEIPTS = "/image/upload/logo/defaultLogo.png";
export const DEFAULT_SETTINGS_FIRST_LOGIN = {
  "logo": null,
  "alamat": "Jl. Raya No. 123, Kota Jakarta",
  "adminFee": {
    "type": "fixed",
    "ranges": [],
    "fixedValue": 2500,
    "multiplier": {
      "fee": 2500,
      "step": 10000
    }
  },
  "shopName": "StrukApp Digital",
  "reference": {
    "type": "limited",
    "digitLimit": 10
  }
}

export const DefaultConfigLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 6,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 2,
    "marginBottom": 8
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 2,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "marginBottom": 10
  },
  {
    "id": "3",
    "gap": 2,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 10,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 16,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "marginBottom": 5
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "BANK",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "BCA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "REKENING",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 3,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "marginBottom": 30
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 2,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 17,
    "alignment": "center",
    "marginTop": 5,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2.4
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "bold",
    "marginBottom": 40,
    "letterSpacing": 0
  }
];

export const DefaultEwalletLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 17,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 6,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 16,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 2,
    "marginBottom": 8
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 2,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "marginBottom": 10
  },
  {
    "id": "3",
    "gap": 2,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 10,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 16,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "marginBottom": 5
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "E-WALLET",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "BCA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NO. HP",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 3,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "marginBottom": 30
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 2,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 17,
    "alignment": "center",
    "marginTop": 5,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2.4
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "bold",
    "marginBottom": 40,
    "letterSpacing": 0
  }
]

export const DefaultListrikLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 6,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 16,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 2,
    "marginBottom": 8
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 2,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "marginBottom": 10
  },
  {
    "id": "3",
    "gap": 2,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 10,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 16,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "marginBottom": 5
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 15,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NO. METER",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 3,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "marginBottom": 30
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 2,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 17,
    "alignment": "center",
    "marginTop": 5,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2.4
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "bold",
    "marginBottom": 40,
    "letterSpacing": 0
  }
]